services:
  worker:
    build:
      context: .
    command: celery -A tasks.task:app worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env.prod
    environment:
      - PYTHONPATH=/app

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  redis:
    image: "redis:7"
    ports:
      - "6379:6379"

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: